global:
  scrape_interval: 15s

scrape_configs:
  - job_name: clickhouse
    metrics_path: /metrics
    static_configs:
      - targets:
          - ch-s1-r1:9363
          - ch-s1-r2:9363
          - ch-s2-r1:9363
          - ch-s2-r2:9363

  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
